// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjJnC1ONzuYpSi65chPREdmFQ4TxtAoww',
    appId: '1:820349955175:web:54863bd90422afe46578c2',
    messagingSenderId: '820349955175',
    projectId: 'fir-project-ab982',
    authDomain: 'fir-project-ab982.firebaseapp.com',
    storageBucket: 'fir-project-ab982.appspot.com',
    measurementId: 'G-CBPDZ5CHDG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPzpirTsq_tm5pzv3hKPt0cLpG-a98rqA',
    appId: '1:820349955175:android:8d3e76a267587c376578c2',
    messagingSenderId: '820349955175',
    projectId: 'fir-project-ab982',
    storageBucket: 'fir-project-ab982.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSBRw4LE-o-eguQpZi5gP1PtBmIyA-k4M',
    appId: '1:820349955175:ios:4bbc7285912506bb6578c2',
    messagingSenderId: '820349955175',
    projectId: 'fir-project-ab982',
    storageBucket: 'fir-project-ab982.appspot.com',
    iosBundleId: 'com.example.firebaseProject1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSBRw4LE-o-eguQpZi5gP1PtBmIyA-k4M',
    appId: '1:820349955175:ios:4bbc7285912506bb6578c2',
    messagingSenderId: '820349955175',
    projectId: 'fir-project-ab982',
    storageBucket: 'fir-project-ab982.appspot.com',
    iosBundleId: 'com.example.firebaseProject1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjJnC1ONzuYpSi65chPREdmFQ4TxtAoww',
    appId: '1:820349955175:web:58c73b5cb0668af46578c2',
    messagingSenderId: '820349955175',
    projectId: 'fir-project-ab982',
    authDomain: 'fir-project-ab982.firebaseapp.com',
    storageBucket: 'fir-project-ab982.appspot.com',
    measurementId: 'G-PZ26BS33PM',
  );
}
